### PR TITLE
PR: Add GitHub CI + Dependabot fixes issue #12

### PR DESCRIPTION
**Pull request by nelsonic**
Micro PR to add GitHub CI and Dependabot to the project. 
Fixes: #12 & #13

### CODE REVIEW

**Comment by nelsonic** [comment]
@SimonLab totally not urgent. Hope you're not looking at this on the weekend! ☀️

**Comment by SimonLab** [comment]
I'll udpate the dependencies and rerun the tests as it's been a while this PR has been open

**Comment by nelsonic** [comment]
Thanks @SimonLab 🙏

**Comment by nelsonic** [comment]
@SimonLab the build was passing above. ✅ 
Merging it would let @dependabot do the updating. 🤖 
Worst-case scenario we'd need to update the `ci.yml` file, e.g: https://github.com/dwyl/hits/commit/6d0cc8515000d3cc443889eab177a1580e8ca2d4 🧑‍💻 
And then let the bot do the work of updating `deps`. 🙏

**Comment by SimonLab** [comment]
I've updated `ci.yml` file and the tests are now running.
There is one test failing and a few warnings:
image

But this match what I have also on localhost.

**Comment by SimonLab** [comment]
The failing test is:
https://github.com/dwyl/content/blob/f9a0ab43530113eb5de550a3a003d7ae00b5d8d9/test/phoenix_wildcard_redirect_test.exs#L73-L77

```elixir
conn = call(Router, :get, "/notfound.json") 
```
Will match the wildcard route:
https://github.com/dwyl/content/blob/f9a0ab43530113eb5de550a3a003d7ae00b5d8d9/test/phoenix_wildcard_redirect_test.exs#L53

and call the controller:
https://github.com/dwyl/content/blob/f9a0ab43530113eb5de550a3a003d7ae00b5d8d9/test/phoenix_wildcard_redirect_test.exs#L28-L38

The function `Content.wildcard_redirect(conn, params, PhoenixWildcardRidrectTest.Router) ` is defined as:

https://github.com/dwyl/content/blob/f9a0ab43530113eb5de550a3a003d7ae00b5d8d9/lib/content.ex#L111-L117

However `Enum.find` returns `nil` for the `route` and the call to `route.plug` break, this is why we have the error: `key :plug not found in: nill.`

**Comment by nelsonic** [comment]
@SimonLab thanks for updating. All improvements are very welcome. 🙏 
Apologies for not answering faster, I saw it was still assigned to you and didn't think there was any ***`action`*** required on my side. 👍 

Please merge when you can so this is off our collective backlog. 👌

**Pull request merged**
